on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python environment setup
        uses: ./.github/workflows/setup-python.yaml

      - name: 🔍 Run pylint
        run: |
          pylint digesting_feed

      - name: 🔍 Run ruff
        run: |
          ruff check digesting_feed

      - name: 🔍 Run black check
        run: |
          black --check digesting_feed

      - name: 🧪 Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
